name: rebar_counter
package_name: com.example.rebarcounting
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

  #--------------- PACKAGES ------------------#



dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.1
  connectivity_plus: ^6.0.4
  image_picker: ^1.1.2
  logger: ^2.4.0
  flutter_spinkit: ^5.2.0
  rive: ^0.12.4

  #image_crop_plus_updated:
  #path: packages/image_crop_plus
  flutter_drawing_board: ^0.9.2    
  #path: packages/flutter_drawing_board
  image_gallery_saver: ^2.0.3
  colorpicker_flutter: ^1.0.3
  syncfusion_flutter_pdfviewer: ^24.2.8
  flutter_share: ^2.0.0






  #firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1


  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  tflite_flutter: ^0.10.4
  image: ^3.0.1
  dotted_border: ^2.1.0


  #--------------- ./ PACKAGES END ------------------#




dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_launcher_icons: "^0.11.0"
  #remove_alpha_ios: true

  flutter_launcher_icons:
  flutter_lints: ^3.0.0

flutter:
 
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/Rebar_AutoLabeling.ipynb
    - assets/rebar_preTrained_model.tflite
    - assets/logos/
    - assets/images/
    - assets/icons/

